== Writing Your First Python Code

Estimated time needed: *25* minutes

=== Objectives

After completing this lab you will be able to:

* Write basic code in Python
* Work with various types of data in Python
* Convert the data from one type to another
* Use expressions and variables to perform operations

Table of Contents

....
<ul>
    <li>
        <a href="https://#hello">Say "Hello" to the world in Python</a>
        <ul>
            <li><a href="https://version/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">What version of Python are we using?</a></li>
            <li><a href="https://comments/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Writing comments in Python</a></li>
            <li><a href="https://errors/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Errors in Python</a></li>
            <li><a href="https://python_error/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Does Python know about your error before it runs your code?</a></li>
            <li><a href="https://exercise/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Exercise: Your First Program</a></li>
        </ul>
    </li>
    <li>
        <a href="https://#types_objects">Types of objects in Python</a>
        <ul>
            <li><a href="https://int/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Integers</a></li>
            <li><a href="https://float/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Floats</a></li>
            <li><a href="https://convert/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Converting from one object type to a different object type</a></li>
            <li><a href="https://bool/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Boolean data type</a></li>
            <li><a href="https://exer_type/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Exercise: Types</a></li>
        </ul>
    </li>
    <li>
        <a href="https://#https://exp/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01ressions">Expressions and Variables</a>
        <ul>
            <li><a href="exp">Expressions</a></li>
            <li><a href="https://exer_exp/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Exercise: Expressions</a></li>
            <li><a href="https://var/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Variables</a></li>
            <li><a href="https://exer_exp_var/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Exercise: Expression and Variables in Python</a></li>
        </ul>
    </li>
</ul>
<p>
    Estimated time needed: <strong>25 min</strong>
</p>
....

Say ``Hello'' to the world in Python

When learning a new programming language, it is customary to start with
an ``hello world'' example. As simple as it is, this one line of code
will ensure that we know how to print a string in output and how to
execute code within cells in a notebook.




+*In[1]:*+
[source, ipython3]
----
# Try your first Python output

print('Hello, Python!')
----


+*Out[1]:*+
----
Hello, Python!
----

After executing the cell above, you should see that Python prints Hello,
Python!. Congratulations on running your first Python code!

....
[Tip:] <code>print()</code> is a function. You passed the string <code>'Hello, Python!'</code> as an argument to instruct Python on what to print.
....

What version of Python are we using?

There are two popular versions of the Python programming language in use
today: Python 2 and Python 3. The Python community has decided to move
on from Python 2 to Python 3, and many popular libraries have announced
that they will no longer support Python 2.

Since Python 3 is the future, in this course we will be using it
exclusively. How do we know that our notebook is executed by a Python 3
runtime? We can look in the top-right hand corner of this notebook and
see ``Python 3''.

We can also ask Python directly and obtain a detailed answer. Try
executing the following code:


+*In[2]:*+
[source, ipython3]
----
# Check the Python Version

import sys
print(sys.version)
----


+*Out[2]:*+
----
3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) 
[GCC 7.3.0]
----

....
[Tip:] <code>sys</code> is a built-in module that contains many system-specific parameters and functions, including the Python version in use. Before using it, we must explictly <code>import</code> it.
....

Writing comments in Python

In addition to writing code, note that it’s always a good idea to add
comments to your code. It will help others understand what you were
trying to accomplish (the reason why you wrote a given snippet of code).
Not only does this help other people understand your code, it can also
serve as a reminder to you when you come back to it weeks or months
later.

To write comments in Python, use the number symbol # before writing your
comment. When you run your code, Python will ignore everything past the
# on a given line.


+*In[3]:*+
[source, ipython3]
----
# Practice on writing comments

print('Hello, Python!') # This line prints a string
# print('Hi')
----


+*Out[3]:*+
----
Hello, Python!
----

After executing the cell above, you should notice that This line prints
a string did not appear in the output, because it was a comment (and
thus ignored by Python).

The second line was also not executed because print(`Hi') was preceded
by the number sign (#) as well! Since this isn’t an explanatory comment
from the programmer, but an actual line of code, we might say that the
programmer commented out that second line of code.

Errors in Python

Everyone makes mistakes. For many types of mistakes, Python will tell
you that you have made a mistake by giving you an error message. It is
important to read error messages carefully to really understand where
you made a mistake and how you may go about correcting it.

For example, if you spell print as frint, Python will display an error
message. Give it a try:


+*In[4]:*+
[source, ipython3]
----
# Print string as error message

frint("Hello, Python!")
----


+*Out[4]:*+
----

    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-4-313a1769a8a5> in <module>
          1 # Print string as error message
          2 
    ----> 3 frint("Hello, Python!")
    

    NameError: name 'frint' is not defined

----

The error message tells you:

where the error occurred (more useful in large notebook cells or
scripts), and

what kind of error it was (NameError)

Here, Python attempted to run the function frint, but could not
determine what frint is since it’s not a built-in function and it has
not been previously defined by us either.

You’ll notice that if we make a different type of mistake, by forgetting
to close the string, we’ll obtain a different error (i.e., a
SyntaxError). Try it below:


+*In[5]:*+
[source, ipython3]
----
# Try to see built-in error message

print("Hello, Python!)
----


+*Out[5]:*+
----

      File "<ipython-input-5-f0b5a635e1a2>", line 3
        print("Hello, Python!)
                              ^
    SyntaxError: EOL while scanning string literal


----

Does Python know about your error before it runs your code?

Python is what is called an interpreted language. Compiled languages
examine your entire program at compile time, and are able to warn you
about a whole class of errors prior to execution. In contrast, Python
interprets your script line by line as it executes it. Python will stop
executing the entire program when it encounters an error (unless the
error is expected and handled by the programmer, a more advanced subject
that we’ll cover later on in this course).

Try to run the code in the cell below and see what happens:


+*In[6]:*+
[source, ipython3]
----
# Print string and error to see the running order

print("This will be printed")
frint("This will cause an error")
print("This will NOT be printed")
----


+*Out[6]:*+
----
This will be printed


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-6-af59af1b345d> in <module>
          2 
          3 print("This will be printed")
    ----> 4 frint("This will cause an error")
          5 print("This will NOT be printed")


    NameError: name 'frint' is not defined

----

Exercise: Your First Program

Generations of programmers have started their coding careers by simply
printing ``Hello, world!''. You will be following in their footsteps.

In the code cell below, use the print() function to print out the
phrase: Hello, world!


+*In[7]:*+
[source, ipython3]
----
# Write your code below. Don't forget to press Shift+Enter to execute the cell
print("Hello, world!")
----


+*Out[7]:*+
----
Hello, world!
----

Click here for the solution

[source,python]
----
print("Hello, world!")
----

Now, let’s enhance your code with a comment. In the code cell below,
print out the phrase: Hello, world! and comment it with the phrase Print
the traditional hello world all in one line of code.


+*In[9]:*+
[source, ipython3]
----
# Write your code below. Don't forget to press Shift+Enter to execute the cell
print("Hello, world") 
#Print the traditional hello world
----


+*Out[9]:*+
----
Hello, world
----

Click here for the solution

[source,python]
----
print("Hello, world!") # Print the traditional hello world
----



Types of objects in Python

Python is an object-oriented language. There are many different types of
objects in Python. Let’s start with the most common object types:
strings, integers and floats. Anytime you write words (text) in Python,
you’re using character strings (strings for short). The most common
numbers, on the other hand, are integers (e.g. -1, 0, 100) and floats,
which represent real numbers (e.g. 3.14, -42.0).



The following code cells contain some examples.


+*In[ ]:*+
[source, ipython3]
----
# Integer

11
----


+*In[ ]:*+
[source, ipython3]
----
# Float

2.14
----


+*In[ ]:*+
[source, ipython3]
----
# String

"Hello, Python 101!"
----

You can get Python to tell you the type of an expression by using the
built-in type() function. You’ll notice that Python refers to integers
as int, floats as float, and character strings as str.


+*In[ ]:*+
[source, ipython3]
----
# Type of 12

type(12)
----


+*In[ ]:*+
[source, ipython3]
----
# Type of 2.14

type(2.14)
----


+*In[ ]:*+
[source, ipython3]
----
# Type of "Hello, Python 101!"

type("Hello, Python 101!")
----

In the code cell below, use the type() function to check the object type
of 12.0.


+*In[10]:*+
[source, ipython3]
----
# Write your code below. Don't forget to press Shift+Enter to execute the cell
type(12.0)
----


+*Out[10]:*+
----float----

Click here for the solution

[source,python]
----
type(12.0)
----

Integers

Here are some examples of integers. Integers can be negative or positive
numbers:



We can verify this is the case by using, you guessed it, the type()
function:


+*In[11]:*+
[source, ipython3]
----
# Print the type of -1

type(-1)
----


+*Out[11]:*+
----int----


+*In[12]:*+
[source, ipython3]
----
# Print the type of 4

type(4)
----


+*Out[12]:*+
----int----


+*In[13]:*+
[source, ipython3]
----
# Print the type of 0

type(0)
----


+*Out[13]:*+
----int----

Floats

Floats represent real numbers; they are a superset of integer numbers
but also include ``numbers with decimals''. There are some limitations
when it comes to machines representing real numbers, but floating point
numbers are a good representation in most cases. You can learn more
about the specifics of floats for your runtime environment, by checking
the value of sys.float_info. This will also tell you what’s the largest
and smallest number that can be represented with them.

Once again, can test some examples with the type() function:


+*In[14]:*+
[source, ipython3]
----
# Print the type of 1.0

type(1.0) # Notice that 1 is an int, and 1.0 is a float
----


+*Out[14]:*+
----float----


+*In[15]:*+
[source, ipython3]
----
# Print the type of 0.5

type(0.5)
----


+*Out[15]:*+
----float----


+*In[16]:*+
[source, ipython3]
----
# Print the type of 0.56

type(0.56)
----


+*Out[16]:*+
----float----


+*In[17]:*+
[source, ipython3]
----
# System settings about float type

sys.float_info
----


+*Out[17]:*+
----sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)----

Converting from one object type to a different object type

You can change the type of the object in Python; this is called
typecasting. For example, you can convert an integer into a float
(e.g. 2 to 2.0).

Let’s try it:


+*In[18]:*+
[source, ipython3]
----
# Verify that this is an integer

type(2)
----


+*Out[18]:*+
----int----

Converting integers to floats

Let’s cast integer 2 to float:


+*In[19]:*+
[source, ipython3]
----
# Convert 2 to a float

float(2)
----


+*Out[19]:*+
----2.0----


+*In[20]:*+
[source, ipython3]
----
# Convert integer 2 to a float and check its type

type(float(2))
----


+*Out[20]:*+
----float----

When we convert an integer into a float, we don’t really change the
value (i.e., the significand) of the number. However, if we cast a float
into an integer, we could potentially lose some information. For
example, if we cast the float 1.1 to integer we will get 1 and lose the
decimal information (i.e., 0.1):


+*In[21]:*+
[source, ipython3]
----
# Casting 1.1 to integer will result in loss of information

int(1.1)
----


+*Out[21]:*+
----1----

Converting from strings to integers or floats

Sometimes, we can have a string that contains a number within it. If
this is the case, we can cast that string that represents a number into
an integer using int():


+*In[22]:*+
[source, ipython3]
----
# Convert a string into an integer

int('1')
----


+*Out[22]:*+
----1----

But if you try to do so with a string that is not a perfect match for a
number, you’ll get an error. Try the following:


+*In[23]:*+
[source, ipython3]
----
# Convert a string into an integer with error

int('1 or 2 people')
----


+*Out[23]:*+
----

    ---------------------------------------------------------------------------

    ValueError                                Traceback (most recent call last)

    <ipython-input-23-b78145d165c7> in <module>
          1 # Convert a string into an integer with error
          2 
    ----> 3 int('1 or 2 people')
    

    ValueError: invalid literal for int() with base 10: '1 or 2 people'

----

You can also convert strings containing floating point numbers into
float objects:


+*In[24]:*+
[source, ipython3]
----
# Convert the string "1.2" into a float

float('1.2')
----


+*Out[24]:*+
----1.2----

....
[Tip:] Note that strings can be represented with single quotes (<code>'1.2'</code>) or double quotes (<code>"1.2"</code>), but you can't mix both (e.g., <code>"1.2'</code>).
....

Converting numbers to strings

If we can convert strings to numbers, it is only natural to assume that
we can convert numbers to strings, right?


+*In[25]:*+
[source, ipython3]
----
# Convert an integer to a string

str(1)

----


+*Out[25]:*+
----'1'----

And there is no reason why we shouldn’t be able to make floats into
strings as well:


+*In[26]:*+
[source, ipython3]
----
# Convert a float to a string

str(1.2)
----


+*Out[26]:*+
----'1.2'----

Boolean data type

Boolean is another important type in Python. An object of type Boolean
can take on one of two values: True or False:


+*In[27]:*+
[source, ipython3]
----
# Value true

True
----


+*Out[27]:*+
----True----

Notice that the value True has an uppercase ``T''. The same is true for
False (i.e. you must use the uppercase ``F'').


+*In[31]:*+
[source, ipython3]
----
# Value false

False
----


+*Out[31]:*+
----False----

When you ask Python to display the type of a boolean object it will show
bool which stands for boolean:


+*In[32]:*+
[source, ipython3]
----
# Type of True

type(True)
----


+*Out[32]:*+
----bool----


+*In[33]:*+
[source, ipython3]
----
# Type of False

type(False)
----


+*Out[33]:*+
----bool----

We can cast boolean objects to other data types. If we cast a boolean
with a value of True to an integer or float we will get a one. If we
cast a boolean with a value of False to an integer or float we will get
a zero. Similarly, if we cast a 1 to a Boolean, you get a True. And if
we cast a 0 to a Boolean we will get a False. Let’s give it a try:


+*In[34]:*+
[source, ipython3]
----
# Convert True to int

int(True)
----


+*Out[34]:*+
----1----


+*In[35]:*+
[source, ipython3]
----
# Convert 1 to boolean

bool(1)
----


+*Out[35]:*+
----True----


+*In[36]:*+
[source, ipython3]
----
# Convert 0 to boolean

bool(0)
----


+*Out[36]:*+
----False----


+*In[37]:*+
[source, ipython3]
----
# Convert True to float

float(True)
----


+*Out[37]:*+
----1.0----

Exercise: Types

What is the data type of the result of: 6 / 2?


+*In[40]:*+
[source, ipython3]
----
# Write your code below. Don't forget to press Shift+Enter to execute the cell
type(6/2) #float
----


+*Out[40]:*+
----float----

Click here for the solution

[source,python]
----
type(6/2) # float
----

What is the type of the result of: 6 // 2? (Note the double slash //.)


+*In[41]:*+
[source, ipython3]
----
# Write your code below. Don't forget to press Shift+Enter to execute the cell
type(6//2) #int
----


+*Out[41]:*+
----int----

Click here for the solution

[source,python]
----
type(6//2) # int, as the double slashes stand for integer division 
----



Expression and Variables

Expressions

Expressions in Python can include operations among compatible types
(e.g., integers and floats). For example, basic arithmetic operations
like adding multiple numbers:


+*In[42]:*+
[source, ipython3]
----
# Addition operation expression

43 + 60 + 16 + 41
----


+*Out[42]:*+
----160----

We can perform subtraction operations using the minus operator. In this
case the result is a negative number:


+*In[43]:*+
[source, ipython3]
----
# Subtraction operation expression

50 - 60
----


+*Out[43]:*+
-----10----

We can do multiplication using an asterisk:


+*In[44]:*+
[source, ipython3]
----
# Multiplication operation expression

5 * 5
----


+*Out[44]:*+
----25----

We can also perform division with the forward slash:


+*In[48]:*+
[source, ipython3]
----
# Division operation expression
(25 / 5)
----


+*Out[48]:*+
----5.0----


+*In[46]:*+
[source, ipython3]
----
# Division operation expression

25 / 6
----


+*Out[46]:*+
----4.166666666666667----

As seen in the quiz above, we can use the double slash for integer
division, where the result is rounded down to the nearest integer:


+*In[49]:*+
[source, ipython3]
----
# Integer division operation expression

25 // 5
----


+*Out[49]:*+
----5----


+*In[50]:*+
[source, ipython3]
----
# Integer division operation expression

25 // 6
----


+*Out[50]:*+
----4----

Exercise: Expression

Let’s write an expression that calculates how many hours there are in
160 minutes:


+*In[52]:*+
[source, ipython3]
----
# Write your code below. Don't forget to press Shift+Enter to execute the cell
160/60 #hours in 160 minutes
----


+*Out[52]:*+
----2.6666666666666665----

Click here for the solution

[source,python]
----
160/60 

# Or 

160//60
----

Python follows well accepted mathematical conventions when evaluating
mathematical expressions. In the following example, Python adds 30 to
the result of the multiplication (i.e., 120).


+*In[53]:*+
[source, ipython3]
----
# Mathematical expression

30 + 2 * 60
----


+*Out[53]:*+
----150----

And just like mathematics, expressions enclosed in parentheses have
priority. So the following multiplies 32 by 60.


+*In[54]:*+
[source, ipython3]
----
# Mathematical expression

(30 + 2) * 60
----


+*Out[54]:*+
----1920----

Variables

Just like with most programming languages, we can store values in
variables, so we can use them later on. For example:


+*In[56]:*+
[source, ipython3]
----
# Store value into variable

x = 43 + 60 + 16 + 41
----

To see the value of x in a Notebook, we can simply place it on the last
line of a cell:


+*In[57]:*+
[source, ipython3]
----
# Print out the value in variable

x
----


+*Out[57]:*+
----160----

We can also perform operations on x and save the result to a new
variable:


+*In[58]:*+
[source, ipython3]
----
# Use another variable to store the result of the operation between variable and value

y = x / 60
y
----


+*Out[58]:*+
----2.6666666666666665----

If we save a value to an existing variable, the new value will overwrite
the previous value:


+*In[59]:*+
[source, ipython3]
----
# Overwrite variable with new value

x = x / 60
x
----


+*Out[59]:*+
----2.6666666666666665----

It’s a good practice to use meaningful variable names, so you and others
can read the code and understand it more easily:


+*In[60]:*+
[source, ipython3]
----
# Name the variables meaningfully

total_min = 43 + 42 + 57 # Total length of albums in minutes
total_min
----


+*Out[60]:*+
----142----


+*In[61]:*+
[source, ipython3]
----
# Name the variables meaningfully

total_hours = total_min / 60 # Total length of albums in hours 
total_hours
----


+*Out[61]:*+
----2.3666666666666667----

In the cells above we added the length of three albums in minutes and
stored it in total_min. We then divided it by 60 to calculate total
length total_hours in hours. You can also do it all at once in a single
expression, as long as you use parenthesis to add the albums length
before you divide, as shown below.


+*In[62]:*+
[source, ipython3]
----
# Complicate expression

total_hours = (43 + 42 + 57) / 60  # Total hours in a single expression
total_hours
----


+*Out[62]:*+
----2.3666666666666667----

If you’d rather have total hours as an integer, you can of course
replace the floating point division with integer division (i.e., //).

Exercise: Expression and Variables in Python

What is the value of x where x = 3 + 2 * 2


+*In[64]:*+
[source, ipython3]
----
# Write your code below. Don't forget to press Shift+Enter to execute the cell
x = 3 + 2 * 2
x 
----


+*Out[64]:*+
----7----

Click here for the solution

[source,python]
----
7
----

What is the value of y where y = (3 + 2) * 2?


+*In[65]:*+
[source, ipython3]
----
# Write your code below. Don't forget to press Shift+Enter to execute the cell
y = (3 + 2) * 2
y
----


+*Out[65]:*+
----10----

Click here for the solution

[source,python]
----
10
----

What is the value of z where z = x + y?


+*In[66]:*+
[source, ipython3]
----
# Write your code below. Don't forget to press Shift+Enter to execute the cell
z = x + y
z
----


+*Out[66]:*+
----17----

Click here for the solution

[source,python]
----
17
----

The last exercise!

Congratulations, you have completed your first lesson and hands-on lab
in Python. However, there is one more thing you need to do. The Data
Science community encourages sharing work. The best way to share and
showcase your work is to share it on GitHub. By sharing your notebook on
GitHub you are not only building your reputation with fellow data
scientists, but you can also show it off when applying for a job. Even
though this was your first piece of work, it is never too early to start
building good habits. So, please read and follow this article to learn
how to share your work.

== Author

Joseph Santarcangelo

== Other contributors

Mavis Zhou

== Change Log

[cols=",,,",options="header",]
|===
|Date (YYYY-MM-DD) |Version |Changed By |Change Description
|2020-08-26 |2.0 |Lavanya |Moved lab to course repo in GitLab
| | | |
| | | |
|===

##

© IBM Corporation 2020. All rights reserved.
